# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_paid', models.BooleanField(default=True)),
                ('rent', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rent_paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rent_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RentPayment'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer'),
        ),
    ]
