# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_constant_total_rent_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constant',
            name='total_rent_to_pay',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_rent_to_pay',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
