# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170529_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rent_obj',
        ),
        migrations.AddField(
            model_name='transaction',
            name='rent_obj',
            field=models.ManyToManyField(to='main.RentPayment'),
        ),
    ]
