# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170530_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='rent_paid',
            field=models.BooleanField(default=False),
        ),
    ]
